// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CountryController from "./country_controller"
application.register("country", CountryController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import StateController from "./state_controller"
application.register("state", StateController)
